config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'

  get 'errors/unacceptable'

  get 'errors/internal_error'

  devise_for :users
  get '/profile', to: 'users#show', as: :user_profile
  root to: 'static_pages#home'

  # Static pages
  get '/home',                to: 'static_pages#home'
  get '/about',               to: 'static_pages#about'
  get '/help',                to: 'static_pages#help'
  get '/about',               to: 'static_pages#about'
  get '/support_project',     to: 'static_pages#support_project'
  #get '/funny_tutorial',     to: 'static_pages#funny_tutorial'

  # GameSessions
  get '/start_game', to: 'game_sessions#start_game', as: :start_game
  get    '/waiting_status',   to: 'game_sessions#start_game'
  post   '/cancel_waiting',   to: 'game_sessions#cancel_waiting'
  get '/game_page', to: 'game_sessions#game_page', as: :game_page
  post   '/code',             to: 'game_sessions#set_code'
  get    '/code',             to: 'game_sessions#get_code'
  get '/simulation', to: 'game_sessions#simulation', as: :simulation
  post '/finish_game', to: 'game_sessions#finish_game', as: :finish_game
  get '/demonstration', to: 'game_sessions#demonstration', as: :demonstration

  get '404', :to => 'errors#not_found'
  get '422', :to => 'errors#unacceptable'
  get '500', :to => 'errors#internal_error'
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  include StaticPagesHelper
  layout('application', only: :home)

  before_filter(:choose_language, except: :home)

  def home
    flash[:alert] = nil
  end

  def help
  end

  def funny_tutorial
  end

  def about
  end

  private
    # Выбрать язык в зависимости от параметров адресной строки (по-умолчанию: 'en')
    def choose_language
      @lang = params[:lang] || 'en'
      @lang = 'en' if (@lang != 'ru' && @lang != 'en')
      render_true_page
    end

    # Составить правильный адрес в зависимости от языка
    def render_true_page
      render full_page_name
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
  def full_page_name
    action_name + '_' + @lang
  end
end

app/views/static_pages/funny_tutorial_ru.html.erb
<%provide :title, 'Funny tutorial'%>
<%provide :head do%>
  <%= stylesheet_link_tag 'static_pages/code-highlight', 'static_pages/help'%>
<% end %>

<%provide :body do%>
  <div id="header">
    <h1>\ <%=link_to 'AI - Project', root_url%> \ Funny tutorial </h1>
    <h3>Write your own AI!</h3>
  </div>

  <p>Приветствую вас на этой странице, призванной помочь вам разобраться в этом нелегком игровом мире.
  И помогут нам в этом два закадычных товарища.</p>

  <p>Это Боб, он Юнит.</p>
  <%= image_tag 'game_sessions/unit.png', width: '10%'%>
  <p>А это — Джордж, он Снаряд.</p>
  <%= image_tag 'game_sessions/shell_dark.png', width: '10%'%>

  <h2>Боб:</h2>
  <ul>
    <li>Отличный Юнит</li>
    <li>У него есть стратегия на любой случай</li>
    <li>Круглый (его радиус = Unit::Radius)</li>
    <li>Умеет ходить (unit.go_to)</li>
    <li>Текущее местонахождение: (unit.location)</li>
    <li>Умеет призывать Джорджа (unit.shoot_to)</li>
  </ul>

  <h2>Джордж:</h2>
  <ul>
    <li>Прекрасный снаряд</li>
    <li>Несколько вспыльчив</li>
    <li>Большой и круглый (его радиус = Shell::Radius)</li>
    <li>Умеет летать (до shell.destination)</li>
    <li>На данный момент находится в (shell.location)</li>
    <li>Имеет неопределенное количество братьев — близнецов</li>
  </ul>


  <h2>Немного об игровом мире</h2>
  <div id="about-game-world" class="description">
    <strong>Мир</strong> представляет из себя квадрат со стороной (World::MapSize).
    <p class = "short-descr">В мире Боба и Джорджа время течет, как в пошаговой стратегии.
      За 1 шаг Боб может пройти в общей сложности (World::GoToDistanceLimit).
      Также за игровой шаг в мире может случиться много интересного — Джордж пролетит еще 1  игровой метр,
      Боб пройдет половину игрового мира и т.д. И чтобы Боб и Джордж не тратили шаги попросту, их число ограничено (World::TackLimit).</p>


    <p class = "short-descr">В мире Боба и Джорджа есть также единица времени аналогичная реальным секундам.
      Назовем ее игровой секундой. 1 шаг может длиться разное количество секунд, в зависимости от того,
      что Боб пожелает сделать за этот шаг.</p>

    <p>Пусть в игровом мире будет аналогия реальному метру. Назовем его — игровым метром.
      На рисунке пусть это будет длина оранжевой линии.</p>
    <%= image_tag 'static_pages/game_meter.png', width: '20%'%>
  </div>


  <p>Вспомним всем известную формулу равномерного прямолинейного движения V = S / t. Отсюда получаем скорость.</p>
  Ниже представлена таблица единиц измерения нашего игрового мира.

  <table border="1">
    <tr>
      <th>Величина</th>
      <th>Единица измерения</th>
      <th>Сокращение</th>
    </tr>

    <tr><td>S (расстояние)</td><td>игровой метр</td><td>и.м.</td></tr>
    <tr><td>T (Время)</td><td>игровая секунда</td><td>и.с.</td></tr>
    <tr><td>V (Скорость)</td><td>игровой метр / игровая секунда</td><td>и.м. / и.с.</td></tr>
  </table>

  <h2>Жизнь Боба и Джорджа</h2>

  <p class="short-descr">Боб не только юнит, он еще и отличный волшебник.
    И как у всякого уважающего себя волшебника, у него есть манна.
    У него ее может быть (Unit::MaxMP), но сейчас у него ее (unit.mp).
    Так же Боб обладает запасом здоровья. Его у него может быть (Unit::MaxHP).
    Но сейчас у него его (unit.hp).</p>


  <p class="short-descr">Если у Боба возникают проблемы с кем — то, он может потратить немного манны (World::ShootCosts) и призвать Джорджа(unit.shoot_to(x,y)).
    Увы, дело это нелегкое и на призыв Джорда, уходит около World::ShellDelay секунд</p>

  <p class="short-descr">Призванный Джордж летит навстречу судьбе, туда, куда послал его Боб
    и наносит урон величиной (Shell::Damage) первому встретившемуся бедолаге.
    Джордж обычно очень зол тем, что Боб вызывает его слишком часто.
    Если бы Боб попался Джорджу на пути — беды было не миновать.
    Поэтому Боб, умудренный горьким опытом, призывает Джорджа на расстоянии (ShootDistance).</p>

  <p class="short-descr">Иногда мир Боба и Джорджа пересекается с другими мирами.
    Из них приходят другие юниты со своими снарядами. И тогда происходит битва.</p>

  <p>У каждого уважающего себя Боба должна быть стратегия на любой случай жизни, даже на вторжение другого Боба.</p>
  <h3>О стратегии</h3>
  Каждый уважающий себя Боб понимает язык программирования Ruby.
  <!-- Так выглядит код, подсвеченный редактором http://dumpz.org/1677903/html/-->
  <div class="highlight"><pre><div id="lc1"><span class="k">class</span> <span class="nc">Strategy</span>
  </div><div id="lc2">  <span class="kp">attr_accessor</span> <span class="ss">:my_unit</span><span class="p">,</span> <span class="ss">:info</span>
  </div><div id="lc3">
  </div><div id="lc4">  <span class="k">def</span> <span class="nf">initialize</span>
  </div><div id="lc5">    <span class="vi">@my_unit</span> <span class="o">=</span> <span class="no">Unit</span><span class="o">.</span><span class="n">new</span>  <span class="c1"># Это Боб! Поприветствуем его</span>
  </div><div id="lc6">    <span class="vi">@info</span>    <span class="o">=</span> <span class="no">World</span><span class="o">.</span><span class="n">new</span> <span class="c1"># А это мир, в котором живет Боб</span>
  </div><div id="lc7">  <span class="k">end</span>
  </div><div id="lc8">
  </div><div id="lc9">  <span class="k">def</span> <span class="nf">move</span>
  </div><div id="lc10">  <span class="c1"># Здесь будет описаны действия Боба на все случаи его жизни</span>
  </div><div id="lc11">  <span class="k">end</span>
  </div><div id="lc12"><span class="k">end</span>
  </div></pre></div>


  <p class = "short-descr">И вот миры пересеклись. Боба и его незнакомого противника переместили на исходные позиции.
    Выбор Исходной позиции юнита зависит от неведомых нам обстоятельств.
    Но это или точка с координатами (1;1) или (World::MapSize – 1;  World::MapSize – 1).</p>

  <p class = "short-descr">Мы на точке (1;1).
    Другой волшебник настроен агрессивно.
    Что же делать?</p>


  <p>Попробуем прощупать его оборону. Выстрелим в него пару раз.</p>
  <!-- Так выглядит код, подсвеченный редактором http://dumpz.org/1677904/html/-->
  <div class="highlight"><pre><div id="lc1"><span class="k">class</span> <span class="nc">Strategy</span>
  </div><div id="lc2">  <span class="kp">attr_accessor</span> <span class="ss">:my_unit</span><span class="p">,</span> <span class="ss">:info</span>
  </div><div id="lc3">
  </div><div id="lc4">  <span class="k">def</span> <span class="nf">initialize</span>
  </div><div id="lc5">    <span class="vi">@my_unit</span> <span class="o">=</span> <span class="no">Unit</span><span class="o">.</span><span class="n">new</span>  <span class="c1"># Это Боб! Поприветствуем его</span>
  </div><div id="lc6">    <span class="vi">@info</span>    <span class="o">=</span> <span class="no">World</span><span class="o">.</span><span class="n">new</span> <span class="c1"># А это мир, в котором живет Боб</span>
  </div><div id="lc7">  <span class="k">end</span>
  </div><div id="lc8">
  </div><div id="lc9">  <span class="k">def</span> <span class="nf">move</span>
  </div><div id="lc10">    <span class="vi">@my_unit</span><span class="o">.</span><span class="n">shoot_to</span><span class="p">(</span><span class="mi">9</span><span class="p">,</span><span class="mi">9</span><span class="p">)</span>
  </div><div id="lc11">    <span class="vi">@my_unit</span><span class="o">.</span><span class="n">shoot_to</span><span class="p">(</span><span class="mi">9</span><span class="p">,</span><span class="mi">9</span><span class="p">)</span>
  </div><div id="lc12">  <span class="k">end</span>
  </div><div id="lc13"><span class="k">end</span>
  </div></pre></div>
  И пошло, поехало.


  <h2>Свод правил Боба</h2>
  <ul>
    <li>Не пытаться разрушить свой любимый мир попытками перейти за пределы карты</li>
    <li>Не стрелять за пределы карты в попытках попасть в юнитов в других мирах</li>
    <li>Не делать бессмысленных действий (пройти 0 метров)</li>
    <li>Не заставлять Великого Обработчика ждать решения слишком долго (больше 1 секунды)</li>
  </ul>
<% end %>

app/views/static_pages/home.html.erb
<% provide :title, 'AI-Project'%>

<% provide :head do %>
    <%= stylesheet_link_tag 'static_pages/home' %>
<% end %>

<% provide :body do %>
    <div id="title">
      <h1> AI Project </h1>
      <p>Write your own AI!</p>
      <!--TODO check do user havs game and send him to continue action-->
      <%= link_to start_game_path, id: 'start-game', method: :get,
                  'data-toggle' => "tooltip",
                  'title' =>"Game with real player with time limitations. \nYou can't leave this game before it ends" do %>
          Start or continue <br>multiplayer game
          <% end %>
      <%= link_to demonstration_path, id: 'demonstration', method: :get,
                  'data-toggle' => "tooltip",
                  'title' =>"Game with bots without time limitations.\n You can leave it at any time" do %>
          Start or continue <br> solo game
      <% end %>
    </div>

    <div id="text-info">
      <div id="description">
        <h2>About</h2>
        <p>
          On this site you can write AI using <%= link_to 'Ruby', 'https://www.ruby-lang.org/en/' %> language
          and let it fight against AIs written by other players
          AI - Project can give you new knowledge, skills, and a lot of fun!
          Just sign up to start this journey.
        </p>
        <%= link_to 'More info', 'about' %>
      </div>

      <div id="links">
        <h2>Additional links</h2>
        <!--TODO -->
        <ul>
          <li>Habrahabr link</li>
          <li>Creator link</li>
          <li>Github link</li>
        </ul>
      </div>
    </div>

    <div id="media">
      <%= video_tag(["vid2.webm", "vid2.mp4"], loop: true, autoplay: true, poster: 'static_pages/video-poster.png') %>
    </div>
<% end %>