config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'

  get 'errors/unacceptable'

  get 'errors/internal_error'

  devise_for :users
  get '/profile', to: 'users#show', as: :user_profile
  root to: 'static_pages#home'

  # Static pages
  get '/home',                to: 'static_pages#home'
  get '/about',               to: 'static_pages#about'
  get '/help',                to: 'static_pages#help'
  get '/about',               to: 'static_pages#about'
  get '/support_project',     to: 'static_pages#support_project'
  #get '/funny_tutorial',     to: 'static_pages#funny_tutorial'

  # GameSessions
  get '/start_game', to: 'game_sessions#start_game', as: :start_game
  get    '/waiting_status',   to: 'game_sessions#start_game'
  post   '/cancel_waiting',   to: 'game_sessions#cancel_waiting'
  get '/game_page', to: 'game_sessions#game_page', as: :game_page
  post   '/code',             to: 'game_sessions#set_code'
  get    '/code',             to: 'game_sessions#get_code'
  get '/simulation', to: 'game_sessions#simulation', as: :simulation
  post '/finish_game', to: 'game_sessions#finish_game', as: :finish_game
  get '/demonstration', to: 'game_sessions#demonstration', as: :demonstration

  get '404', :to => 'errors#not_found'
  get '422', :to => 'errors#unacceptable'
  get '500', :to => 'errors#internal_error'
end

app/views/partials/_navbar.html.erb
<!--TODO bigger navbar-->
<div class="navbar navbar-default">
  <div class="navbar-header">
    <b><%= link_to 'AI - Project', root_url, class: 'navbar-brand', method: :get %></b>
  </div>

  <div class="container-fluid">
    <ul class="nav navbar-nav">
      <li><%= link_to 'Help', 'help', method: :get %></li>
      <li><%= link_to 'About', 'about', method: :get %></li>
    </ul>

    <ul class="nav navbar-nav navbar-right">
      <% if signed_in? %>
          <li>
            <%= link_to user_profile_path, method: :get do%>
                <span class="glyphicon glyphicon-star-empty"></span> Profile
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do%>
                <span class="glyphicon glyphicon-log-out"></span> Sign out
            <% end %>
          </li>
      <% else %>
          <li>
            <%= link_to new_user_registration_path, method: :get do %>
                <span class="glyphicon glyphicon-user"></span> Sign up
            <% end %>
          </li>
          <li>
            <%= link_to new_user_session_path, method: :get do%>
                <span class="glyphicon glyphicon-log-in"></span> Login
            <% end %>
          </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/partials/_time_panel.html.erb
<% if @game.time_remaining > 0 %>
    <div id="timer">
      <span class="glyphicon glyphicon-time"></span>
      <%= content_tag :span, '', 'data-time-remaining' => @game.time_remaining, :id => 'timer-value' %>
    </div>
<% else %>
    <%= button_to finish_game_path, :id => 'btn-finish-game', :method => :post do %>
        <span class="glyphicon glyphicon-flag"></span> Finish game
    <% end %>
<% end %>