config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'

  get 'errors/unacceptable'

  get 'errors/internal_error'

  devise_for :users
  get '/profile', to: 'users#show', as: :user_profile
  root to: 'static_pages#home'

  # Static pages
  get '/home',                to: 'static_pages#home'
  get '/about',               to: 'static_pages#about'
  get '/help',                to: 'static_pages#help'
  get '/about',               to: 'static_pages#about'
  get '/support_project',     to: 'static_pages#support_project'
  #get '/funny_tutorial',     to: 'static_pages#funny_tutorial'

  # GameSessions
  get '/start_game', to: 'game_sessions#start_game', as: :start_game
  get    '/waiting_status',   to: 'game_sessions#start_game'
  post   '/cancel_waiting',   to: 'game_sessions#cancel_waiting'
  get '/game_page', to: 'game_sessions#game_page', as: :game_page
  post   '/code',             to: 'game_sessions#set_code'
  get    '/code',             to: 'game_sessions#get_code'
  get '/simulation', to: 'game_sessions#simulation', as: :simulation
  post '/finish_game', to: 'game_sessions#finish_game', as: :finish_game
  get '/demonstration', to: 'game_sessions#demonstration', as: :demonstration

  get '404', :to => 'errors#not_found'
  get '422', :to => 'errors#unacceptable'
  get '500', :to => 'errors#internal_error'
end

app/models/game_session.rb
class GameSession < ActiveRecord::Base
  has_many :players, dependent: :nullify
  has_many :users, through: :players

  # GameSession duration in seconds
  def self.game_duration
    60.minutes
  end

  def self.players_count
    2
  end

  def self.other_players_count
    GameSession.players_count - 1
  end

  def is_empty?
    !has_players?
  end

  # rewrite this
  def has_players?
    players(true).any? { |player| player.is_in_game && !player.user.is_bot }
  end

  def winner
    if winner_id.present?
      User.find(winner_id)
    else
      nil
    end
  end

  def is_active?
    @is_active = time_remaining > 0
  end

  # Returns remaining time in seconds
  def time_remaining
    time_lasts = end_time - Time.now
    if time_lasts < 0
      time_lasts = 0
    end

    time_lasts.round
  end

  private
    def end_time
      self.created_at.to_time + GameSession.game_duration
    end
end

app/controllers/game_sessions_controller.rb
class GameSessionsController < ApplicationController
  include GameSessionsHelper::SyntaxErrors
  include GameSessionsHelper::Simulation

  before_filter :authenticate_user!
  before_filter :preset_variables
  before_filter :check_has_game,       except: [:start_game, :cancel_waiting, :demonstration]
  before_filter :check_has_no_game,    only:    :demonstration
  before_filter :check_game_is_active, only:    :set_code
  before_filter :check_game_is_ended,  only:    :finish_game
  after_action  :destroy,              only:    :finish_game

  # Идентификаторы ожидающих игры пользователей
  # TODO store it in database
  @@ids_if_waiting = Array.new # TODO change to self.ids_of_waiting

  # Периодически спрашивает, готова ли игра
  # Если игра готова, редирректит на страницу создания / входа игровой сессии
  # +@user+: current_user
  # TODO split it into 2 methods (create_game, continue_game)
  # TODO game session duration should be modifayable (and has default value)
  # TODO Тогда ты сможешь без костылей сделать игровую сессию укороченной длины
  # FIXME is_has_game может быть фильтром для этого экшена, который редиректит на игровую страницу, если игрок уже в игре
  def start_game
    respond_to do |format|
      if game_ready?
        find_or_create_game_session
        format.html { redirect_to :action => :game_page and return }
      else
        format.html { render :start_game and return }
      end

      # TODO вынести это в отдельный экшн
      format.json { render json: { :game_ready => game_ready?, :players_count => @@ids_if_waiting.size }}
    end
  end

  # Удаляет идентификатор игрока из @@ids_of_waiting_players в случае,
  # если тот покинул страницу ожидания
  # +@user+: current_user
  def cancel_waiting
    @@ids_if_waiting.delete @user.id
    head :no_content and return
  end


  # Страница редактором кода и базовыми ссылками
  # +@user+: user
  # +@game+: current_user.game
  def game_page
  end

  # Принимает код игрока, проверяет его на ошибки и сохраняет в БД
  # +@game+: current_user.game
  # +@user+: current_user
  def set_code
    @player_code = params[:player_code]

    errors = syntax_errors(@player_code)
    if syntax_ok? errors
      @user.player.update_attribute(:code, @player_code)
      errors = 'Syntax OK'
    end

    render json: {:errors => errors}
  end

  # Возвращает код игрока
  # +@user+: current_user
  def get_code
    render json: @user.player.code
  end

  # Симуляция
  # +@game+: current_user.game
  # todo we can simulate one times and after that show user cycled battle animation
  def simulation
    respond_to do |format|
      format.html
      format.json do
        @codes = {}
        pg_secure_query do
          @game.players(true).each { |player| @codes[player.user_id] = player.code }
        end

        begin
          # fixme как квариант, можно хранить симулятор в переменной и делать refresh
          @simulator_output = AIProject::Simulator.new(@codes).simulate
        rescue RuntimeError, NameError, Secure::ChildKilledError, Secure::TimeoutError, SecurityError, Timeout::Error => e
          @simulator_output = {errors: e.message}
        end

        if @simulator_output[:errors].nil?
          pg_secure_query {@game.update_attribute(:winner_id, @simulator_output[:options][:winner_id])}
        end

        pg_secure_query {add_players_info_in @simulator_output}

        render json: @simulator_output
      end
    end
  end

  # Выводит результаты игры для игрока при выходе
  # Удаляет игровую сессию, когда все игроки вышли
  # +@user+: current_user
  # +@game+: current_user.game
  def finish_game
    @user.player.update_attribute(:is_in_game, false)
    # TODO destroy players. But players can be used to show code of other players
    # TODO in future, we can do other battle mode - challendge strategies of other players
  end

  # Game with fake players
  # User can easily leave it and start other game
  def demonstration
    # todo nice link here https://github.com/plataformatec/devise/wiki/How-Tos
    # todo we can use this https://github.com/plataformatec/devise/wiki/How-To:-Create-a-guest-user
    # todo ask only email in registration https://github.com/plataformatec/devise/wiki/How-To:-Email-only-sign-up
    @game = DemoGameSession.create
    @player = Player.create(user_id: @user.id, game_session_id: @game.id)
    GameSession.other_players_count.times do |i|
      # TODO we need create module with Strategies samples in lib
      # TODO store class as file (it will be executable) and read it as string to here
      random_password = SecureRandom.hex(8)
      fake_user_id = User.maximum('id') + 1
      fake_user = User.create(email: "bot#{fake_user_id.to_s}@example.com",
                              :password => random_password,
                              :password_confirmation => random_password,
                              is_bot: true)

      fake_player = Player.create(game_session_id: @game.id,
                                  code: Codes::CIRCLE,
                                  user_id: fake_user.id)
      # todo leave players not deleted and show list of them to see player's code
    end
    redirect_to :game_page
  end

  private
    def game_ready?
      unless @@ids_if_waiting.include? @user.id
        @@ids_if_waiting.push @user.id
      end

      enough_players  = @@ids_if_waiting.size >= GameSession.players_count
      game_is_created = @user.game.present?

      enough_players || game_is_created
    end

  # Если игра для нас уже создана, переходим на игровую страницу
  # Если игра для нас не создана, создаем ее
    def find_or_create_game_session
      @@ids_if_waiting.delete @user.id
      @game = @user.game

      if @game.nil?
        # Создаем игрвую сессию
        @game = GameSession.create # fixme задержка до завершения этого экшена вычитается из времени игровой сессии

        # Выбираем игроков
        other_players = [@user.id]
        GameSession.other_players_count.times do
          next_user_id = @@ids_if_waiting.sample
          other_players.push next_user_id
          @@ids_if_waiting.delete next_user_id
        end

        # Создаем игроков
        other_players.each do |user_id|
          Player.create(user_id: user_id, game_session_id: @game.id)
        end
      end
    end

    def increment_winner_statistic
      if @game.winner.present?
        @game.winner.increment(:wins_count).save
      end
    end

  # it was a part of finish_game action,
  # but it caused an interesting behaviour:
  # @game.users.each doent's work due to  @game was destroyed
  # but if i did @users = @game.users before that,
  # finish_game.html.erb searched users in database (not in @users)
    def destroy
      if @game.is_empty?
        increment_winner_statistic

        # destroy bots users
        bots_ids = @game.users.collect {|user| user.id if user.is_bot}
        User.where(id: bots_ids).destroy_all
        @game.players.destroy_all # todo use it in future
        @game.destroy
      end
    end

  # FILTERS
  # ==================================================================================
    def check_has_game
      @game = @user.game
      not_found if @game.nil?
    end

  # Player has game already
  def check_has_no_game
    @game = @user.game
    redirect_to action: :start_game if @game.present?
  end

  # В неактивной игре игроки не имеют права отправлять код
  def check_game_is_active
    unless @game.is_active?
      render_error_head
    end
  end

  # Нельзя покидать игру до ее завершения
  def check_game_is_ended
    if @game.is_active? && !@game.is_a?(DemoGameSession)
      render_error_head
    end
  end

  def preset_variables
    @user = current_user
  end

  def render_error_head
    head 500
  end

  def pg_secure_query
    begin
      yield
    rescue ActiveRecord::StatementInvalid => e
      logger.debug("Connection with PG database was lost")
      logger.debug(e.message)
      ActiveRecord::Base.connection.reconnect!
      yield
    end
  end
end

app/helpers/game_sessions_helper.rb
module GameSessionsHelper
  module SyntaxErrors
    # Возвращает то, что было записано в поток $stderr за время выполнения блока
    def capture_stderr
      previous_stderr = $stderr
      $stderr = StringIO.new
      yield # There are code is executed
      errors = $stderr.string
      $stderr = previous_stderr

      errors
    end

    # Перенаправляем поток ошибок в переменную
    # И пытаемся скомпилировать код игрока
    # Возвращаем то, что было записано в поток
    def syntax_errors( code )
      errors = capture_stderr do
        begin
          RubyVM::InstructionSequence.compile( code )
        rescue SyntaxError
        end
      end
    end

    def syntax_ok?( error_messages )
      error_messages.empty?
    end
  end

  module Simulation
    # Simulation helpers
    # После того, как объект первой удачной стратегии будет создан
    # Эта удачная копия будет существовать сколько угодно времени
    # И последующие оппытки переопределить эту стратегию ни к чему не приведут
    # +@game+ :: game ids
    def remove_previous_strategies_definitions
      @game.user_ids.each { |id| ActiveSupport::Dependencies::remove_constant(get_strategy_constant id) }
    end

    def get_strategy_constant(id)
      # strategy = AIProject::SimulatorMethods::ParseStrategies::Strategy#{player.id}::Strategy.new
      # Why Constant path so big i don't know
      user_const = "AIProject::SimulatorMethods::ParseStrategies::Strategy#{id.to_s}::Strategy".safe_constantize
      if (defined? user_const) == "constant"
        Object.send(:remove_const, user_const)
      end
      "AIProject::SimulatorMethods::ParseStrategies::Strategy#{id.to_s}::Strategy"
    end

    def add_players_info_in(simulator_output)
      simulator_output[:users_info] = {}
      @game.users(true).each do |user|
        simulator_output[:users_info][user.id] = { :name => user.name }
      end
    end
  end
end

app/views/game_sessions/demonstration.html.erb
<% provide :title, "Demonstration" %>
<% provide :head do %>
<% end %>

<% provide :body do %>
<% end %>

app/views/game_sessions/finish_game.html.erb
<% provide :title, 'Finish Game' %>
<% provide :head do %>
  <%= stylesheet_link_tag 'game_sessions/finish_game'%>
<% end %>

<% provide :body do %>
    <h3>
      <%= link_to home_url, id: 'home-link', method: :get do %>
        <span class="glyphicon glyphicon-home"></span> To home page
      <% end %>
    </h3>

    <%= content_tag :div, id: 'message' do |tag| %>
        <% if current_user.id == @game.winner_id %> You are a winner! Congratulations!
        <% else %> Nice try!
        <% end %>
    <% end %>

    <div id="game-results">
      <table class="table table-hover">
        <tr>
          <th>Nickname</th>
          <th>Avatar</th>
          <th>Is winner</th>
        </tr>

        <% @game.users.each do |user| %>
            <tr>
              <th><%= user.name %></th>
              <th><%= image_tag('game_sessions/unit.png') %></th>
              <th>
                <% if @game.winner_id == user.id %>
                    <span class="glyphicon glyphicon-star"></span>
                <% end %>
              </th>
            </tr>
        <% end %>
      </table>
    </div>
<% end %>

app/views/game_sessions/game_page.html.erb
<% provide :title, 'Game page'%>

<% provide :head do %>
  <%= javascript_include_tag 'lib/easytimer', 'game_timer', 'lib/codemirror', 'lib/fullscreen', 'lib/ruby', 'code_io', 'game_page' %>
  <%= stylesheet_link_tag 'game_sessions/game_page', 'game_sessions/mdn-like', 'game_sessions/codemirror', 'lib/fullscreen' %>
  <%= javascript_include_tag 'https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js'%>
  <!-- there is not many difference -load from google or from our site. First option may be better-->
<% end %>

<% provide :body do %>
    <div id="code-window">
      <textarea id="code"><%= @user.player.code %></textarea>

      <div id="errors-window">
        <div id="errors-header">Errors:</div>
        <div id="errors-text">Syntax OK</div>
      </div>
    </div>

    <div id="info-panel">
      <div id="controls">
        <div id="buttons">
          <% if @game.is_active? %>
              <button id="send-code">Send Code</button>
          <% else %>
              <button id="send-code" class="disabled">Send Code</button>
          <% end %>
          <%= link_to "Simulation", simulation_path, id: 'simulation-link', method: :get %>
        </div>

        <div id="game-info">
          <%= render partial: 'partials/time_panel' %>
          <div id="user-info">
            <div id="user-name">Name: <%= @user.name %></div>
          </div>
        </div>

      </div>

      <div id="game-help">
        <%= render partial: 'partials/game_help.html.md' %>
      </div>
    </div>
<% end %>

app/views/game_sessions/simulation.html.erb
<% provide :title, 'Game Simulaion'%>
<% provide :head do %>
  <%= javascript_include_tag 'lib/pixi', 'visualizer'%>
  <%= stylesheet_link_tag 'game_sessions/simulation'%>
<% end %>

<% provide :body do %>
    <div id="controls">
      <%= link_to 'Go back', 'game_page', id: 'back-link', method: :get %>
      <% unless @game.time_remaining > 0 %>
          <div class="btn-group">
            <%= button_to finish_game_path, id: 'btn-finish-game', method: :post do%>
                <span class="glyphicon glyphicon-flag"></span> Finish game
            <% end %>
          </div>
      <% end %>
    </div>

    <div id="errors">
      <div id="errors-header">Errors in simulation</div>
      <div id="errors-text"></div>
    </div>

    <div id="view">
      <div id="please-wait">
        <div id="message-header">Please wait</div>
        <hr>
        <div id="message-body">It takes some time</div>
        <%= image_tag 'game_sessions/squares.gif', id: 'progress-pie' %>
      </div>
    </div>

    <%= content_tag(:div, nil, id: "visualizer-info", style: 'display: none;',
                    data: {background_sprite: image_path('game_sessions/background-xy.jpg'),
                           unit_sprite: image_path('game_sessions/unit.png'),
                           shell_sprite: image_path('game_sessions/shell_dark.png')}) %>
<% end %>

app/views/game_sessions/start_game.html.erb
<% provide :title, 'Page Wait' %>

<% provide :head do %>
  <%= javascript_include_tag 'jquery', 'game_waiting'%>
  <%= stylesheet_link_tag 'game_sessions/page_wait'%>
<% end %>

<% provide :body do %>
    <div id="info">
      <h2 id="message">
        Please, wait. Your game will start as soon as possible.
      </h2>
      <div id='game-status'>
        How many players are waiting: <span class="text-danger" id='players-count'></span>
      </div>
    </div>
    <%= image_tag 'game_sessions/squares.gif', id: 'progress-pie' %>
<% end %>